export const ADD_TO_CART = 'ADD_TO_CART'
export const DELETE_FROM_CART = 'DELETE_FROM_CART'
export const UPDATE_ITEM_UNITS = 'UPDATE_ITEM_UNITS'
export const ADD_ITEM_UNITS = 'ADD_ITEM_UNITS'

export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
