export const ADD_TO_CART = 'ADD_TO_CART'
export const DELETE_FROM_CART = 'DELETE_FROM_CART'
export const UPDATE_ITEM_UNITS = 'UPDATE_ITEM_UNITS'

export const RECEIVE_PRODUCTS_LIST = 'RECEIVE_PRODUCTS_LIST'
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT'
